services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: river-front
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: sh -c "npm run dev"

    stdin_open: true
    tty: true
